export const kpiData = [
  {
    mainLabel: 'Sell Out Volume',
    subLabel: '',
    value: '348,940K',
    yoyLabel: 'YoY: -67,201K ',
    change: -12.85,
    mdlzValue: '144,077K',
    mdlzYoyChange: 'YoY: -28,195K ',
    mdlzIsPositive: false,
    mdlzLabel: 'Volume (Mdlz)',
  },
  {
    mainLabel: 'Sell Out Value',
    subLabel: '',
    value: 'R$302,631K',
    yoyLabel: 'YoY: -R$56,410K ',
    change: -7.70,
    mdlzValue: 'R$148,194K',
    mdlzYoyChange: 'YoY: -R$28,335K ',
    mdlzIsPositive: false,
    mdlzLabel: 'Value (Mdlz)',
  },
  {
    mainLabel: 'Sell Out Units',
    subLabel: '',
    value: '297,284K',
    yoyLabel: 'YoY: -57,627K ',
    change: -12.34,
    mdlzValue: '140,089K',
    mdlzYoyChange: 'YoY: -27,339K ',
    mdlzIsPositive: false,
    mdlzLabel: 'Units (Mdlz)',
  },
  {
    mainLabel: 'Avg Price Per Unit',
    subLabel: '',
    value: 'R$1.02',
    yoyLabel: 'YoY: +R$0.98 ',
    change: 5.30,
    mdlzValue: 'R$1.06',
    mdlzYoyChange: 'YoY: +R$1.04 ',
    mdlzIsPositive: true,
    mdlzLabel: 'Avg Price (Mdlz)',
  },
];